FROM python:3.6.3-slim

# Create app directory
WORKDIR /mnt/auto

# docker build -t registry.cn-shenzhen.aliyuncs.com/test-wss/python3:v0.3 .
# docker push registry.cn-shenzhen.aliyuncs.com/test-wss/python3:v0.1